import { lazy } from 'react'

export const Dashboard = lazy(() => import('./Dashboard'))
export const Altars = lazy(() => import('./Altars'))
export const AIMentor = lazy(() => import('./AIMentor'))
export const RitualTracker = lazy(() => import('./RitualTracker'))
export const SigilLab = lazy(() => import('./SigilLab'))
export const Journal = lazy(() => import('./Journal'))
export const Marketplace = lazy(() => import('./Marketplace'))
export const Settings = lazy(() => import('./Settings'))
export const ForumPage = lazy(() => import('./forum/ForumPage'))
export const KnowledgeGraph = lazy(() => import('./KnowledgeGraph'))
export const DivinationLab = lazy(() => import('./DivinationLab'))
export const ChakraIntelligence = lazy(() => import('./ChakraIntelligence'))
export const CovensPage = lazy(() => import('./CovensPage'))
